# Generated by Django 5.0.4 on 2024-04-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEeduapp', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='files/Categor')),
            ],
        ),
    ]
