# Generated by Django 5.0.4 on 2024-05-09 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEeduapp', '0005_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='files/mentor_profile')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='duration_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEeduapp.mentor'),
        ),
    ]
