# Generated by Django 5.0.4 on 2024-05-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEeduapp', '0006_mentor_video_duration_hours_video_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mentor_name',
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NEeduapp.mentor'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEeduapp.course')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEeduapp.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NEeduapp.course')),
            ],
        ),
    ]
