# Generated by Django 5.0.4 on 2024-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEeduapp', '0007_remove_course_mentor_name_course_mentor_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
