# Generated by Django 5.0.4 on 2024-05-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEeduapp', '0008_mentor_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='length',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='designation',
        ),
        migrations.AlterField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEeduapp.mentor'),
        ),
    ]
