# Generated by Django 5.0.4 on 2024-05-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEeduapp', '0009_remove_course_length_remove_mentor_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
